version: '3.8'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cliniter
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USERNAME: user
      DB_PASSWORD: userpass
      DB_DATABASE: cliniter
    depends_on:
      - mysql
    restart: always
